/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.cleber.machinelearn;

import java.awt.BorderLayout;
import java.util.Random;
import javax.swing.Timer;
import org.jfree.chart.ChartFactory;
import org.jfree.chart.ChartPanel;
import org.jfree.chart.JFreeChart;
import org.jfree.chart.axis.ValueAxis;
import org.jfree.chart.plot.XYPlot;
import org.jfree.data.time.DynamicTimeSeriesCollection;
import org.jfree.data.time.Second;
import org.jfree.data.xy.XYDataset;

/**
 *
 * @author cleber
 */
public class AlgoritmoGeneticoForm extends javax.swing.JFrame {

    private static final Random random = new Random();
    private Populacao pop = new Populacao();
    private Timer timer;
    private Thread t;
    private boolean isRun = false;
    private final DynamicTimeSeriesCollection dataset = new DynamicTimeSeriesCollection(1, 120, new Second());

    /**
     * Creates new form AlgoritmoGenetico
     */
    public AlgoritmoGeneticoForm() {
        initComponents();
        dataset.setTimeBase(new Second());
        dataset.addSeries(valorInicial(), 0, "Gaussian Data");
        JFreeChart chart = createChart(dataset);
        ChartPanel chartPanel = new ChartPanel(chart);
        chartPanel.setBounds(0, 0, 900, 490);
        this.add(chartPanel, BorderLayout.CENTER);

        t = new Thread(new Runnable() {
            @Override
            public void run() {
                while (isRun) {
                    AlgoritmoGenetico ag = new AlgoritmoGenetico(0.8f, 0.001f);
                    pop = ag.executaAG(pop);
                    float[] newData = new float[1];
                    newData[0] = Float.parseFloat(pop.getMediaPopulacao().toString());
                    dataset.advanceTime();
                    dataset.appendData(newData);
                    txtInformacao.setText(pop.printPopulacao());
                    txtMedia.setText(pop.getMediaPopulacao().toString());
                    try {
                        Thread.sleep(100);
                    } catch (Exception e) {
                    }
                }
                btnChamarIndividuo.setEnabled(true);
            }
        });
        t.setDaemon(true);
    }

    private float[] valorInicial() {
        float[] a = new float[1];
        a[0] = 0;
        return a;
    }

    private JFreeChart createChart(final XYDataset dataset) {
        final JFreeChart result = ChartFactory.createTimeSeriesChart(
                "Valores dos Indivíduos", "Tempo", "Fitness", dataset, true, true, false);
        final XYPlot plot = result.getXYPlot();
        ValueAxis domain = plot.getDomainAxis();
        domain.setAutoRange(true);
        ValueAxis range = plot.getRangeAxis();
        range.setRange(0, 1000);
        return result;
    }

    private float randomValue() {
        return (float) (random.nextGaussian() * 100 / 3);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        txtInformacao = new javax.swing.JTextArea();
        btnChamarIndividuo = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        txtMedia = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtInformacao.setColumns(20);
        txtInformacao.setRows(5);
        jScrollPane1.setViewportView(txtInformacao);

        btnChamarIndividuo.setText("Start");
        btnChamarIndividuo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChamarIndividuoActionPerformed(evt);
            }
        });

        jLabel1.setText("Média População:");

        jLabel2.setText("População:");

        jTextField1.setText("jTextField1");

        jLabel3.setText("População:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnChamarIndividuo, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtMedia, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1045, Short.MAX_VALUE)
                        .addContainerGap())))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(24, 24, 24))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addGap(440, 440, 440)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnChamarIndividuo)
                    .addComponent(jLabel1)
                    .addComponent(txtMedia))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnChamarIndividuoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChamarIndividuoActionPerformed

        if (btnChamarIndividuo.getText().equalsIgnoreCase("start")) {
            btnChamarIndividuo.setText("Stop");
            isRun = true;
            t.start();
        } else {
            btnChamarIndividuo.setText("Start");
            isRun = false;
            t.stop();
        }


    }//GEN-LAST:event_btnChamarIndividuoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AlgoritmoGeneticoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AlgoritmoGeneticoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AlgoritmoGeneticoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AlgoritmoGeneticoForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                AlgoritmoGeneticoForm ag = new AlgoritmoGeneticoForm();
                ag.setTitle("Algoritmo Genético - by Cleber Santos");
                ag.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChamarIndividuo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextArea txtInformacao;
    private javax.swing.JLabel txtMedia;
    // End of variables declaration//GEN-END:variables
}
